/**
 * Generated by `createschema contact.Contact 'property:Relationship:Property:SET_NULL; name:Text; phone:Text; unitName?:Text; email?:Text;'`
 */

const { checkOrganizationPermission } = require('@condo/domains/organization/utils/accessSchema')
const get = require('lodash/get')
const { throwAuthenticationError } = require('@condo/domains/common/utils/apolloErrorFormatter')
const { Contact } = require('../utils/serverSchema')
const { checkRelatedOrganizationPermission } = require('@condo/domains/organization/utils/accessSchema')
const { queryOrganizationEmployeeFromRelatedOrganizationFor } = require('@condo/domains/organization/utils/accessSchema')
const { queryOrganizationEmployeeFor } = require('@condo/domains/organization/utils/accessSchema')
const { isObject } = require('lodash')

function getPerUserReadAccess (user, listKey) {
    // return { id_in: ['uid1', 'uid2'] }
    const access = get(user.access, [listKey, 'read']) // return list filter
    if (isObject(access)) return access
    return null
}

async function canReadContacts ({ authentication: { item: user }, listKey, operation, itemId, itemIds, originalInput }) {
    if (!user) return throwAuthenticationError()
    if (user.isAdmin) return {}
    const customAccess = getPerUserReadAccess(user, listKey)
    if (customAccess) return { customAccess }
    const userId = user.id
    return {
        organization: {
            OR: [
                queryOrganizationEmployeeFor(userId),
                queryOrganizationEmployeeFromRelatedOrganizationFor(userId),
            ],
        },
    }
}

function getPerUserManageAccess (user, listKey, operation, fields = []) {
    // operation: create update delete
    // fields: [] for delete action
    // ID...
    const access = get(user.access, [listKey, operation]) // return allow to access fields
    if (!Array.isArray(access)) return null
    const accessSet = new Set(access)
    const difference = new Set(fields.filter(x => !accessSet.has(x)))
    return difference.size === 0 // check only allowed fields!
}

async function canManageContacts ({ authentication: { item: user }, listKey, originalInput, operation, itemId, itemIds, context }) {
    if (!user) return throwAuthenticationError()
    if (user.isAdmin) return true
    const customAccess = getPerUserManageAccess(user, listKey, operation, originalInput ? Object.keys(originalInput) : [])
    if (customAccess !== null) return customAccess
    if (operation === 'create') {
        const organizationId = get(originalInput, ['organization', 'connect', 'id'])
        const canManageRelatedOrganizationContacts = await checkRelatedOrganizationPermission(context, user.id, organizationId, 'canManageContacts')
        if (canManageRelatedOrganizationContacts) {
            return true
        }
        const canManageContacts = await checkOrganizationPermission(context, user.id, organizationId, 'canManageContacts')
        return canManageContacts
    } else if (operation === 'update') {
        const [contact] = await Contact.getAll(context, { id: itemId })
        if (!contact) {
            return false
        }
        const canManageRelatedOrganizationContacts = await checkRelatedOrganizationPermission(context, user.id, contact.organization.id, 'canManageContacts')
        if (canManageRelatedOrganizationContacts) {
            return true
        }
        const canManageContacts = await checkOrganizationPermission(context, user.id, contact.organization.id, 'canManageContacts')
        return canManageContacts
    }
    return false
}

/*
  Rules are logical functions that used for list access, and may return a boolean (meaning
  all or no items are available) or a set of filters that limit the available items.
*/
module.exports = {
    canReadContacts,
    canManageContacts,
}
